services:
  mysql:
    image: mysql:8.0
    container_name: api-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agendasalas
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: api-web
    restart: always
    depends_on:
      - mysql
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8080:8080"

volumes:
  mysql_data: